### ISSUE TITLE
Is this Custom Navigation synonymous with Articles or how can I understand that

### ISSUE THREAD

**Issue by ghost** [mecha-cms/x.pager#1]
Hi Tovic,

For example, I have my articles on my Mecha website at `/article`. Are they also paginated or is it only the case with the shield you use?

The navigation looks great and I like it. Cool Extension !!

**Comment by taufik-nurrohman** [comment]
Yes, it will replace the default index page navigation on any index pages when you put the _pager_ shield on `pages.php` file. You can use conditional statements to disable the nunbered page navigation on specific pages for example:

~~~ .html
<!-- Only show numbered page navigation in snippet pages. -->
<?php if (strpos($url->path . '/', 'snippet/') === 0): ?>
<?php Shield::get('pager/step'); ?>
<?php else: ?>
<nav><?php echo $pager; ?></nav>
<?php endif; ?>
~~~

**Comment by ghost** [comment]
OK, Thanks for the hints!
